# CORES
PRIMARY_COLOR = "#EA1D2F"     
BG_WHITE = "#FFFFFF"
BG_LIGHT = "#F7F7F8"
HOVER_COLOR = "#C41523"
BORDER_COLOR = "#E8E8E8"
...

# FONTES
FONT_TITLE = ("Arial", 14, "bold")
FONT_BUTTON = ("Segoe UI", 9, "bold")
FONT_TERMINAL = ("Consolas", 10)
...

# TELA PRINCIPAL
WINDOW_TITLE = "Suporte Tools"
HEADER_HEIGHT = 70
SIDEBAR_WIDTH = 220
...

# ABAS INTERNAS
PADX_BUTTONS = 2
PADX_SIDEBAR = 12
...
